DEFAULT_CONFIG = {
    "DELETE_CONVERTED_MP3": True,
    "SAMPLE_RATE": 22050,
    "PREPROCESSING_ON": True,
    "SAMPLE_SECONDS": 5,
    "SPLIT_FILTER_TYPE": "quartile",
    "SPLIT_FILTER_CUTOFF": 0.15,
    "TRAIN_TEST_SPLIT": 0.2,
    "BATCH_SIZE": 32,
    "EPOCHS": 5
}